Generic FQDN for 4G/5G
OPENAIRINTERFACE/openair-spgwu-tiny pull request #36
Opened 2021-06-28 15:50 UTC by orion-belt

2021-06-29 07:49 UTC, rdefosse requested changes

2021-06-29 07:49 UTC, rdefosse commented on etc/spgw_u.conf
> +    #FQDN = "gw@GW_ID@.spgw.node.epc.mnc@MNC03@.mcc@MCC@.@REALM@";
You can remove the commented line.

Or better you can explain both formats as comment (the 4G case and the 5G case)

2021-06-29 07:59 UTC, thinhnt1983 commented
Hi @orion-belt it would be better if you can still keep FQDN = "gw@GW_ID@.spgw.node.epc.mnc@MNC03@.mcc@MCC@.@REALM@"; at the beginning of the conf file, since it's for 4G. and we shouldn't touch 4G part. Then you can add a new variable, e.g., FQDN_UPF inside 5G session. Then we process according to 5g flag. What do you think?

2021-06-29 08:25 UTC, orion-belt commented
@thinhnt1983 @rdefosse 
Recommendations are fixed in latest commit.

2021-06-29 15:45 UTC, rdefosse commented on etc/spgw_u.conf
> +       UPF_FQDN_5G  = "@UPF_FQDN_5G@";  #Set FQDN of UPF
@orion-belt @thinhnt1983 

This wlll require to modify at least a few docker-compose in the federation repository.

- `https://github.com/OPENAIRINTERFACE/openair-epc-fed/blob/master/docker-compose/magma-mme-demo/docker-compose.yml`
- `https://github.com/OPENAIRINTERFACE/openair-epc-fed/blob/master/docker-compose/oai-mme-legacy/docker-compose.yml`
- `https://github.com/OPENAIRINTERFACE/openair-epc-fed/blob/master/ci-scripts/dsTesterDockerCompose/docker-compose.tplt`
- `https://github.com/OPENAIRINTERFACE/openair-epc-fed/blob/master/ci-scripts/dsTesterDockerComposeLegacy/docker-compose.tplt`
- `https://github.com/OPENAIRINTERFACE/openair-epc-fed/blob/master/ci-scripts/oai-ran-sanity-check/spgwu.env`

Unless you put a default value in the `entrypoint.sh` like I did for the previous 5G fields.

Raphael

2021-06-30 08:32 UTC, rdefosse approved these changes

2021-07-06 09:18 UTC, thinhnt1983 approved these changes

2021-07-06 11:51 UTC, merged