Display slice info
OPENAIRINTERFACE/openair-spgwu-tiny pull request #60
Opened 2022-06-14 06:53 UTC by orion-belt

2022-06-17 12:09 UTC, lionelgo requested changes

2022-06-17 12:09 UTC, lionelgo commented on src/spgwu/spgwu_config.hpp
> +const uint8_t SST_MAX_STANDARDIZED_VALUE = 127;
should be defined in a file ...23.003..hpp

2022-06-17 14:41 UTC, lionelgo requested changes

2022-06-17 14:41 UTC, lionelgo commented on src/common/3gpp_23.003.h
> +const uint8_t SST_MAX_STANDARDIZED_VALUE = 127;
You may choose preprocessor #define SST_MAX_STANDARDIZED_VALUE ...
or if you use const, you may follow C++ coding guideline k...

2022-06-17 14:53 UTC, lionelgo approved these changes

2022-06-28 13:43 UTC, orion-belt commented
@lionelgo 
Added small commit to handle  `no SD value => 0xFFFFFF (TS 23.003, R16.0.0., 28.4.2)`

2022-06-29 13:12 UTC, merged